version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: don_estate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  parser:
    build: .
    command: python src/parser/telegram_parser.py
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    restart: unless-stopped

  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build: .
    command: python src/bot/main.py
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:
