services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: don_estate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d don_estate"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_init:
    build: .
    command: python init_db.py
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  # parser:
  #   build: .
  #   command: python -m src.parser.telegram_parser
  #   depends_on:
  #     - db_init
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./media:/app/media
  #   restart: unless-stopped

  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db_init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
